# Generated by Django 5.1.7 on 2025-04-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed_stores',
            field=models.ManyToManyField(blank=True, related_name='followers', to='profiles.vendorprofile'),
        ),
    ]
