# Generated by Django 5.1.7 on 2025-04-28 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_remove_product_image_category_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_per_vendor',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_parent__f3c24e_idx',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='parent_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='primary_image',
            new_name='image',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent_category'], name='products_ca_parent__6caaf7_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('vendor', 'name', 'parent_category'), name='unique_category_name_per_vendor'),
        ),
    ]
