# Generated by Django 5.1.7 on 2025-04-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_unique_category_name_per_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(related_name='promotions', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
